server:
  port: 8080
  tomcat:
    accept-count: 600
    max-threads: 600
    min-spare-threads: 100
    max-connections: 10000

spring:
  application:
    name: recommend-server
  profiles:
    active: dev
    include:
      - datasource
      - redis
      - cache
      - monitor
      - feign
  
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recommend?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j2
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 50
        max-idle: 20
        min-idle: 5
        max-wait: 3000ms

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # 缓存配置
  cache:
    type: redis
    redis:
      time-to-live: 300000
      cache-null-values: false

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.recommend.common.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: partial
    default-executor-type: reuse
    default-statement-timeout: 25000
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 推荐系统配置
recommend:
  system:
    version: 1.0.0
    enable-cache: true
    enable-monitor: true
    default-recommend-count: 10
    max-recommend-count: 100
    cache-expire-time: 300
    default-algorithm: hybrid
  
  # 算法配置
  algorithm:
    collaborative-filtering:
      similarity-threshold: 0.1
      neighbor-count: 50
    content-based:
      feature-weight: 0.6
      tag-weight: 0.4
    hybrid:
      cf-weight: 0.4
      cb-weight: 0.6

  # 监控配置
  monitor:
    enable: true
    metrics-interval: 60
    alert-threshold: 0.95
    slow-query-threshold: 1000

# Feign配置
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true

# 日志配置
logging:
  level:
    com.recommend: DEBUG
    org.springframework.cache: DEBUG
    com.alibaba.druid: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

---
# 开发环境配置
spring:
  profiles: dev
  
logging:
  level:
    root: INFO
    com.recommend: DEBUG

---
# 生产环境配置
spring:
  profiles: prod

logging:
  level:
    root: WARN
    com.recommend: INFO
  file:
    name: /var/log/recommend-server/application.log

server:
  tomcat:
    accept-count: 1000
    max-threads: 800
    min-spare-threads: 200
